version: '3.4'

services:
  migrations:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnection=Server=db;Database=MedicalCenter;User=sa;Password=QWERTy!123456789;TrustServerCertificate=True;
    container_name: service-migrations
    image: service-migrations
    build:
      context: ./MedicalCenter
      dockerfile: MedicalCenter.Data/Dockerfile
      target: migrations
    depends_on:
        - db
    healthcheck:
      test: ["CMD", "ping", "127.0.0.1", "-n", "11", ">", "nul"]
      interval: 10s
      timeout: 15s
      retries: 1

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: mssql_api
    environment:
        MSSQL_SA_PASSWORD: "QWERTy!123456789"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "5033:1433"
        - "5034:1434"
    healthcheck:
        interval: 10s
        timeout: 3s
        retries: 10
        start_period: 10s
        test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "QWERTy!123456789" -Q "SELECT * FROM Doctors" || exit 1
  api:
    image: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnection=Server=db;Database=MedicalCenter;User=sa;Password=QWERTy!123456789;TrustServerCertificate=True;
    ports:
      - 5000:8080
      - 5001:8081
    build:
      context: ./MedicalCenter
      dockerfile: ./Dockerfile
    depends_on:
      - migrations
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthcheck"]
      interval: 10s
      timeout: 30s
      retries: 3
      
  ui:
    image: ui
    ports:
      - 88:80
    build:
      context: ./MedicalCenter.UI
      dockerfile: ./Dockerfile
      args:
        API_URL: http://localhost:5000/
    depends_on:
      - api